name: Integration Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Setup Environment variables
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .test.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .test.env

      - name: Run migrations
        run: npm run migrate:test:reset

      - name: Seed the database
        run: npm run db:seed:test

      - name: Run test
        run: npm run test
